### PR TITLE
Fix image digest regex

### PR DESCRIPTION
**Pull request by ilyalatt**

### CODE REVIEW

**Comment by ilyalatt** [comment]
Hi! It's needed because

**Comment by ilyalatt** [comment]
Hi! It is needed in my case. I use the registry path without scheme specified like `myregistry.local` instead of `http://myregistry.local`.

**Comment by ilyalatt** [comment]
@philpep ping

**Comment by philpep** [comment]
Merged, thanks!

On my cluster this this "docker://<image>@sha526", just for tracability what version of k8s you use with which container engine ?

**Comment by ilyalatt** [comment]
> Merged, thanks!
> 
> On my cluster this this "docker://@sha526", just for tracability what version of k8s you use with which container engine ?

The k8s version is 1.17.7. The container engine is containerd. It was installed via snap (microk8s package).

**Pull request merged**
